### ISSUE TITLE
[META]: Initial Scope of Managed Resources

### ISSUE THREAD

**Issue by tsouza** [tsouza/terraform-provider-elasticstack#3]
Find below a list of the managed resources targeted for the initial release:
- [ ]  Data Management: Index and Component Templates, ILM, Snapshot, etc - https://github.com/stevewritescode/terraform-provider-elastic-stack/issues/5
- [ ]  Ingest Pipelines
- [ ]  Painless Scripts
- [ ]  Users, Roles, Api Keys and Role Mappings - https://github.com/stevewritescode/terraform-provider-elastic-stack/issues/3
- [ ]  Alerts and Connectors
- [ ]  Security Endpoint - https://github.com/stevewritescode/terraform-provider-elastic-stack/issues/7
